# Generated by Django 4.0.3 on 2022-03-15 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('surveyID', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestionAlternative',
            fields=[
                ('question_alternativeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('questionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SurveyQuestionAlternative-questionID+', to='survey.survey')),
                ('surveyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=512)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('questionID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SurveyQuestionAlternative-questionID+', to='survey.survey')),
                ('surveyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_answerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.surveyquestionalternative')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('questionID', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=255)),
                ('surveyID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
    ]
